apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-replica
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx-deployment-replica
    spec:
      containers:
      - name: nginx-deployment-replica
        image: nginx:1.7.9
        ports:
        - containerPort: 80
