apiVersion: v1 
kind: ReplicationController
metadata:
  name: nginx-replica
spec:
  replicas: 3 
  template:
    metadata:
     labels:
       app: nginx-replica
    spec:
      containers:
      - name: nginx-replica
        image: nginx:latest
        ports:
        - containerPort: 80
